name: "to-publish-to-docker"
description: "to-publish-to-docker"
author: "sidhusaiprasanth@gmail.com"
branding:
  color: black
  icon: arrow-right-circle
inputs:
  docker_username:
    description: Docker username to login
    required: true
  docker_password:
    description: Docker password to login
    required: true
  image_name:
    required: true
    description: Imagename

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4
    - run: |
        echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c 1-7)" >> "$GITHUB_ENV" 
        echo $SHORT_SHA
      shell: bash
    - name: Login Docker
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_password }}
    - uses: docker/metadata-action@v5
      id: meta
      with:
        # images: ${{ secrets.HARBOR_REGISTRY }}/${{ secrets.HARBOR_PROJECT }}/courserepo
        images: ${{ inputs.docker_username }}/${{ inputs.image_name }}
        tags: |
          ${{ env.SHORT_SHA }}
    - uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
